---
- hosts: fedora
  become: yes
  vars_files:
    - config.yaml

  tasks:
    - import_tasks: fedora/dnf.yaml
      when: dnf.enabled
      tags: ["dnf"]

    - import_tasks: fedora/dconf.yaml
      when: dconf.enabled
      tags: ["dconf"]

    - import_tasks: fedora/nvidia.yaml
      when: nvidia.enabled
      tags: ["nvidia"]

    - import_tasks: fedora/docker.yaml
      when: docker.enabled
      tags: ["docker"]

    - import_tasks: fedora/linuxbrew.yaml
      when: linuxbrew.enabled
      tags: ["linuxbrew"]

    - import_tasks: fedora/shell.yaml
      when: shell.enabled
      tags: ["shell"]

    - import_tasks: fedora/sdkman.yaml
      when: sdkman.enabled
      tags: ["sdkman"]

    - name: Reboot
      when: reboot.enabled
      reboot:
        pre_reboot_delay: 0
