---
- name: Install roles
  hosts: all
  vars_prompt:
    - name: ansible_become_pass
      prompt: Password for SUDO_ASKPASS
  roles:
    - role: applications
    - role: configs
    - role: geerlingguy.mac.dock
      when: configure_dock
