---
- name: Tap Homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop: "{{ homebrew.taps }}"

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  loop: "{{ homebrew.formulae }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  loop: "{{ homebrew.casks }}"
