---
- name: Import Homebrew tasks
  ansible.builtin.import_tasks: homebrew.yml
  become: false
  when: homebrew.enabled

- name: Import Tizen tasks
  ansible.builtin.import_tasks: tizen.yml
  become: false
  when: tizen.enabled
