---
- name: Ensure Tizen directory exists
  ansible.builtin.file:
    path: "/Users/{{ ansible_user }}/Developer/tizen"
    state: directory
    mode: "0755"

- name: Download Tizen CLI Installer
  ansible.builtin.get_url:
    url: "https://download.tizen.org/sdk/Installer/tizen-studio_{{ tizen.version }}/web-cli_Tizen_Studio_{{ tizen.version }}_macos-64.bin"
    checksum: sha256:e83b419b91e267619da4da5c8fc13e079294c5491ca4a82ad88e56ae39d92700
    dest: "/Users/{{ ansible_user }}/Developer/tizen/web-cli_Tizen_Studio_{{ tizen.version }}_macos-64.bin"
    mode: "0755"

- name: Install Tizen Studio
  ansible.builtin.command:
    argv:
      - "/Users/{{ ansible_user }}/Developer/tizen/web-cli_Tizen_Studio_{{ tizen.version }}_macos-64.bin"
      - "--accept-license"
      - "/Users/{{ ansible_user }}/Developer/tizen/tizen-studio"
    creates: "/Users/{{ ansible_user }}/Developer/tizen/tizen-studio"
