---
- name: Configure autohide flag
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "{{ dock.autohide }}"

- name: Configure dock magnification
  block:
    - name: Set dock magnification flag
      community.general.osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: bool
        value: "{{ dock.magnify }}"

    - name: Set dock magnification size
      community.general.osx_defaults:
        domain: com.apple.dock
        key: largesize
        type: int
        value: "{{ dock.magnify_size }}"

- name: Configure application minification
  block:
    - name: Set minimize to application flag
      community.general.osx_defaults:
        domain: com.apple.dock
        key: minimize-to-application
        type: bool
        value: "{{ dock.minimize_to_application }}"

    - name: Set minimize animation effect
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: string
        value: "{{ dock.mineffect }}"

- name: Configure dock orientation
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: "{{ dock.orientation }}"

- name: Configure show recents flag
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: "{{ dock.show_recents }}"

- name: Configure dock size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: "{{ dock.size }}"

- name: Configure hot corners
  block:
    - name: Set corner action
      community.general.osx_defaults:
        domain: com.apple.dock
        key: "wvous-{{ item.key }}-corner"
        type: int
        value: "{{ item.value }}"
      loop: "{{ dock.hotcorners | dict2items }}"

    - name: Set corner modifier
      community.general.osx_defaults:
        domain: com.apple.dock
        key: "wvous-{{ item.key }}-modifier"
        type: bool
        value: "0"
      loop: "{{ dock.hotcorners | dict2items }}"
