---
- name: Ensure Ghostty configuration directory exists
  ansible.builtin.file:
    path: "/Users/{{ ansible_user }}/.config/ghostty"
    state: directory
    mode: "0755"

- name: Copy Ghostty configuration
  ansible.builtin.copy:
    src: "files/ghostty.config"
    dest: "/Users/{{ ansible_user }}/.config/ghostty/config"
    mode: "0644"
