---
- name: Configure Ghostty
  ansible.builtin.import_tasks: ghostty.yml
  become: false

- name: Configure zsh
  ansible.builtin.import_tasks: zsh.yml
  become: false

- name: Configure dock
  ansible.builtin.import_tasks: dock.yml
  become: false
  notify:
    - Restart dock

- name: Configure system menu
  ansible.builtin.import_tasks: menubar.yml
  become: false
