---
- name: Remove old docker packages
  dnf:
    name: "{{ item }}"
    state: absent
  loop: "{{ docker.old_docker_packages }}"

- name: Add docker repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Verify fingerprint
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/fedora/gpg"
    fingerprint: "060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35"

- name: Install dnf packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ docker.new_docker_packages }}"

- name: Enable and start docker service
  command: systemctl enable docker.service --now

- name: Adding existing user "{{ user.name }}" to group docker
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes

- name: NVIDIA Docker
  when: nvidia.enabled
  block:
    - name: Add NVIDIA yum repository
      get_url:
        url: https://nvidia.github.io/nvidia-docker/centos8/nvidia-docker.repo
        dest: /etc/yum.repos.d/nvidia-docker.repo
        mode: "0644"
        force: yes

    - name: Import NVIDIA GPG keys
      ansible.builtin.rpm_key:
        state: present
        key: "https://nvidia.github.io/nvidia-docker/gpgkey"

    - name: Install nvidia-docker2
      dnf:
        name: "nvidia-docker2"
        enablerepo: "nvidia-docker"
        state: latest

    - name: Update nvidia-container-runtime config.toml
      lineinfile:
        path: /etc/nvidia-container-runtime/config.toml
        search_string: "#no-cgroups = false"
        line: "no-cgroups = true"
        owner: root
        group: root
        mode: "0644"

    - name: Restart docker service
      command: systemctl restart docker.service